# Plotly

## Data Visualziation
Data Visualization is the graphical representation of information and data. By using visual elements like charts, graphs, and maps, data visualization tools provide an accessible way to see and understand trends, outliers, and patterns in data

## Plotly
- Plotly is a Python library which is used to design graphs, especially interactive graphs.

- It can plot various graphs and charts like histogram, barplot, boxplot, spreadplot, and many more.
- It is mainly used in data analysis as well as financial analysis. Plotly is an interactive visualization library.

### Benefits of using plolty:
- Plotly is interactive, the graphs can be zoomed in and out, downloaded as a PNG file, hovered over to see the data points, and much more.
- Plotly is compatible with Pandas DataFrames, making it easy to plot data directly from CSVs.
- Plotly can help making animated plots, which can be very useful for visualizing data over time.
- Plotly can be used to style interactive graphs with Jupyter notebook.
- Plotly with dash is a great choice for creating interactive dashboards that can be deployed on the web.

In [1]:
# import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

In [2]:
# remove warning
import warnings
warnings.filterwarnings('ignore')

In [3]:
# load dataset of dimond from seaborn
df = sns.load_dataset('diamonds')
df= df.sample(frac=0.1, random_state=10) # sample 10% of the data for faster processing
df.head()

       carat        cut color clarity  depth  table  price     x     y     z
8018    1.01    Premium     E     SI1   61.7   56.0   4330  6.44  6.39  3.96
1583    0.70  Very Good     D     VS1   60.4   58.0   3008  5.71  5.78  3.47
9138    1.13  Very Good     H     SI2   59.8   59.0   4537  6.75  6.82  4.06
2787    0.76      Ideal     F     VS2   61.0   55.0   3257  5.89  5.92  3.60
52429   0.70    Premium     I    VVS1   61.2   59.0   2513  5.65  5.69  3.47

In [4]:
# reindex the data
df.reset_index(drop=True, inplace=True)

In [5]:
df.head()

   carat        cut color clarity  depth  table  price     x     y     z
0   1.01    Premium     E     SI1   61.7   56.0   4330  6.44  6.39  3.96
1   0.70  Very Good     D     VS1   60.4   58.0   3008  5.71  5.78  3.47
2   1.13  Very Good     H     SI2   59.8   59.0   4537  6.75  6.82  4.06
3   0.76      Ideal     F     VS2   61.0   55.0   3257  5.89  5.92  3.60
4   0.70    Premium     I    VVS1   61.2   59.0   2513  5.65  5.69  3.47

In [6]:
# scatter plot
fig = px.scatter(df, x='carat', y='price', color='cut')
fig.update_traces(marker=dict(line=dict(width=1, color='DarkSlateGrey')))
fig.update_layout(title='Diamonds Price vs Carat', xaxis_title='Carat', yaxis_title='Price')
fig.show()

- we used color argument in it.

In [7]:
# Plot a line chart (example: mean price by carat)
mean_price_by_carat = df.groupby('carat')['price'].mean().reset_index()
fig = px.line(mean_price_by_carat, x='carat', y='price', title='Mean Price by Carat')
fig.update_traces(line=dict(width=2, color='blue'))
fig.update_layout(title='Mean Price by Carat', xaxis_title='Carat', yaxis_title='Mean Price')
fig.show()

In [8]:
# line plot
fig = px.line(df, x='carat', y='price', color='cut', line_group='cut', hover_name='clarity')
fig.update_traces(marker=dict(line=dict(width=1, color='DarkSlateGrey')))
fig.update_layout(title='Diamonds Price vs Carat', xaxis_title='Carat', yaxis_title='Price')
fig.show()

In [9]:
# bar plot
fig = px.bar(df, x='cut', y='price', color='cut', title='Average Price by Cut')
fig.update_traces(marker=dict(line=dict(width=1, color='DarkSlateGrey')))
fig.update_layout(title='Average Price by Cut', xaxis_title='Cut', yaxis_title='Average Price')
fig.show()

In [10]:
df_stats = df.groupby('clarity')['price'].agg(['mean', 'std']).reset_index()
df_stats.head()

# Bar plot for average price per cut category
fig = px.bar(df_stats, x='clarity', y='mean', error_y='std', 
             title='Average Price by Cut', color='clarity')
fig.show()

In [11]:
# histogram plot
fig = px.histogram(df, x='price', color='cut', title='Carat Distribution by Cut')
fig.update_traces(marker=dict(line=dict(width=1, color='DarkSlateGrey')))
fig.update_layout(title='Carat Distribution by Cut', xaxis_title='Carat', yaxis_title='Count')
fig.show()

In [12]:
# Density Contour plot
fig = px.density_contour(df, x='carat', y='price', color='cut', title='Density Contour of Carat vs Price')
fig.update_traces(contours_coloring='fill', contours_showlabels=True)
fig.update_layout(title='Density Contour of Carat vs Price', xaxis_title='Carat', yaxis_title='Price')
fig.show()

In [13]:
# Box plot
fig = px.box(df, x='cut', y='price', color='cut', title='Box Plot of Price by Cut')
fig.update_traces(marker=dict(line=dict(width=1, color='DarkSlateGrey')))
# outlier points
points = 'suspected outliers'
fig.update_layout(title='Box Plot of Price by Cut', xaxis_title='Cut', yaxis_title='Price')
fig.show()

In [14]:
# box plot
fig = px.box(df, x='cut', y='price', color='clarity',
             # outliers
            points='suspectedoutliers', # 'outliers', 'suspectedoutliers'
            title='Price Distribution by Cut',
            labels={'price':'Price ($)', 'cut':'Cut', 'clarity':'Clarity'}
            )
fig.show()

In [15]:
# volin plot
fig = px.violin(df, x='cut', y='price', color='cut', box=True,
                 title='Violin Plot of Price by Cut')
fig.update_traces(marker=dict(line=dict(width=1, color='DarkSlateGrey')))
fig.show()

In [16]:
# density plot
fig = px.density_contour(df, x='carat', y='price', color='cut',
                          title='Density Contour of Carat vs Price')
fig.update_traces(contours_coloring='fill', contours_showlabels=True)
fig.update_layout(title='Density Contour of Carat vs Price', xaxis_title='Carat', yaxis_title='Price')
fig.show()

In [17]:
from plotly.subplots import make_subplots

# subplot
fig = make_subplots(rows=2, cols=2,
                    specs=[[{'type':'scatter'}, {'type':'scatter'}],
                           [{'type':'scatter'}, {'type':'scatter'}]],
                    subplot_titles=('Scatter Plot', 'Line Plot', 'Bar Plot', 'Box Plot'))
fig.add_trace(go.Scatter(x=df['carat'], y=df['price'], mode='markers', name='Scatter Plot'), row=1, col=1)
fig.add_trace(go.Scatter(x=df['carat'], y=df['price'], mode='lines', name='Line Plot'), row=1, col=2)
fig.add_trace(go.Bar(x=df['cut'], y=df['price'], name='Bar Plot'), row=2, col=1)
fig.add_trace(go.Box(x=df['cut'], y=df['price'], name='Box Plot'), row=2, col=2)
fig.update_layout(title='Subplots of Different Plot Types', height=800, width=800)
fig.show()

In [18]:
from plotly.subplots import make_subplots

# Create subplots
fig = make_subplots(rows=1, cols=2, 
                    subplot_titles=('Carat vs Price', 
                                    'Density Heatmap of Carat vs Price'))

# Scatter plot of carat vs price
scatter = px.scatter(df, x='carat', y='price').data[0]
fig.add_trace(scatter, row=1, col=1)

# Density heatmap of carat vs price
heatmap = px.density_heatmap(df, x='carat', y='price').data[0]
fig.add_trace(heatmap, row=1, col=2)

# Update layout
fig.update_layout(title_text='Carat vs Price and Density Heatmap of Carat vs Price')
fig.show()

In [19]:
#heatmap plot
fig = px.density_heatmap(df, x='carat', y='price', z='cut', title='Density Heatmap of Carat vs Price')
fig.update_layout(title='Density Heatmap of Carat vs Price', xaxis_title='Carat', yaxis_title='Price')
fig.show()

In [20]:
# creat heatmap of correlation matrix of only numerical columns
corr = df[['carat', 'depth', 'table', 'price', 'x', 'y', 'z']].corr()
fig = go.Figure(data=go.Heatmap(x=corr.index.values, 
                                y=corr.columns.values, 
                                z=corr.values, 
                                colorscale='Reds')) 
# colorscale can be 'Viridis', 'Cividis', 'Blues', 'Greens', 'Reds', 'Oranges', 'YlOrRd', 'YlGnBu', 'RdBu', 'Picnic', 'Rainbow', 'Portland', 'Jet', 'Hot', 'Blackbody', 'Earth', 'Electric', 'Plasma', 'Magma', 'Inferno', 'Cividis'
fig.show()

## 3D Plots

In [21]:
# 3D scatter plot
fig = px.scatter_3d(df, x='carat', y='depth', z='price', color='cut', title='3D Scatter Plot of Carat, Depth and Price')
fig.update_traces(marker=dict(line=dict(width=1, color='DarkSlateGrey')))
fig.update_layout(
	title='3D Scatter Plot of Carat, Depth and Price',
	scene=dict(
		xaxis_title='Carat',
		yaxis_title='Depth',
		zaxis_title='Price'
	)
)
fig.show()

In [22]:
# 3D scatter plot
fig = px.scatter_3d(df, 
                    x='carat', 
                    y='depth', 
                    z='price', 
                    color='cut', 
                    title='3D Scatter Plot of Carat, Depth, and Price')
fig.show()

In [23]:
# 3D line plot
fig = px.line_3d(df, x='carat', y='depth', z='price', color='cut', title='3D Line Plot of Carat, Depth and Price')
fig.update_traces(marker=dict(line=dict(width=1, color='DarkSlateGrey')))
fig.update_layout(
    title='3D Line Plot of Carat, Depth and Price',
    scene=dict(
        xaxis_title='Carat',
        yaxis_title='Depth',
        zaxis_title='Price'
    )
)
fig.show()

## Other Plots

In [24]:
# Bubble chart with carat and price, using depth as size
fig = px.scatter(df, x='carat', y='price', size='depth', color='cut', hover_name='clarity', title='Bubble Chart of Carat vs Price with Depth as Size')
fig.update_traces(marker=dict(line=dict(width=1, color='DarkSlateGrey')))
fig.update_layout(title='Bubble Chart of Carat vs Price with Depth as Size', xaxis_title='Carat', yaxis_title='Price')
fig.show()

In [25]:
# Area chart
fig = px.area(df, x='carat', y='price', color='cut', title='Area Chart of Carat vs Price')
sorted_df = df.sort_values(by='carat')
fig.update_traces(marker=dict(line=dict(width=1, color='DarkSlateGrey')))
fig.update_layout(title='Area Chart of Carat vs Price', xaxis_title='Carat', yaxis_title='Price')
fig.show()

In [26]:
# Pie chart
fig = px.pie(df, names='cut', values='price', title='Pie Chart of Price by Cut')
fig.update_traces(marker=dict(line=dict(width=1, color='DarkSlateGrey')), 
                  pull=[0.1 if label == 'Premium' else 0 for label in df['cut']],
                  textinfo='label+percent', 
                  textfont_size=12, 
                  marker_colors=px.colors.qualitative.Set3)
fig.update_layout(title='Pie Chart of Price by Cut', xaxis_title='Cut', yaxis_title='Price')
fig.show()

In [27]:
# treemap plot
fig = px.treemap(df, path=['cut', 'clarity'], values='price', title='Treemap of Price by Cut and Clarity')
fig.update_traces(marker=dict(line=dict(width=1, color='DarkSlateGrey')))
fig.update_layout(title='Treemap of Price by Cut and Clarity', xaxis_title='Cut', yaxis_title='Price')
fig.show()

In [28]:
# parallel corrdinates plot
fig = px.parallel_coordinates(df, color='price',
                                # dimensions=['carat', 'depth'], # choose columns 
                              title='Parallel Coordinates Plot')
fig.show()

In [29]:
# scatter matrix plot
fig = px.scatter_matrix(df, dimensions=['carat', 'depth', 'price'], color='cut', title='Scatter Matrix Plot')
fig.update_traces(diagonal_visible=False, marker=dict(line=dict(width=1, color='DarkSlateGrey')))
fig.update_layout(title='Scatter Matrix Plot', xaxis_title='Carat', yaxis_title='Price')
fig.show()

In [30]:
# Gantt chart of a random time series data from 2020-01-01 to 2020-01-10
df_gantt = pd.DataFrame({
    'Task': ['Groceries', 'Shopping', 'School', 'Travel', 'Lahore Shadi'],
    'Start': pd.to_datetime(['2024-01-01', '2024-01-03', '2024-01-02', '2024-01-05', '2024-01-06']),
    'Finish': pd.to_datetime(['2024-01-03', '2024-01-06', '2024-01-05', '2024-01-08', '2024-01-10'])
})
print(df_gantt.head())
fig = px.timeline(df_gantt, 
                  x_start='Start', 
                  x_end='Finish', 
                  y='Task', 
                  title='Gantt Chart of Tasks')

           Task      Start     Finish
0     Groceries 2024-01-01 2024-01-03
1      Shopping 2024-01-03 2024-01-06
2        School 2024-01-02 2024-01-05
3        Travel 2024-01-05 2024-01-08
4  Lahore Shadi 2024-01-06 2024-01-10

In [31]:
# strip plot
fig = px.strip(df, x='cut', y='price', color='cut', title='Strip Plot of Price by Cut')
fig.update_traces(marker=dict(line=dict(width=1, color='DarkSlateGrey')))
fig.update_layout(title='Strip Plot of Price by Cut', xaxis_title='Cut', yaxis_title='Price')
fig.show()

In [32]:
# sunburst plot
fig = px.sunburst(df, path=['cut', 'clarity'], values='price', title='Sunburst Plot of Price by Cut and Clarity')
fig.update_traces(marker=dict(line=dict(width=1, color='DarkSlateGrey')))
fig.update_layout(title='Sunburst Plot of Price by Cut and Clarity', xaxis_title='Cut', yaxis_title='Price')
fig.show()
# Save the plot as an HTML file
fig.write_html("sunburst_plot.html")

In [33]:
fig = px.sunburst(df, 
                path=['cut', 'clarity', 'color'],
                values='price',
                title='Sunburst Chart of Diamond Price by Cut, Clarity, and Color')


import plotly.io as pio

# Save the plot as an svg file
pio.write_image(fig, 'sunburst_chart.svg', format='svg')

# 3:59:20

## Marginal Plots using Plotly

In [34]:
# scatter plot with marginal histogram
fig = px.scatter(df, x='carat', y='price', color='cut', marginal_x='histogram', marginal_y='histogram',
                 title='Scatter Plot with Marginal Histograms')
fig.update_traces(marker=dict(line=dict(width=1, color='DarkSlateGrey')))
fig.update_layout(title='Scatter Plot with Marginal Histograms', xaxis_title='Carat', yaxis_title='Price')
fig.show()

In [35]:
# scatter plot with marginal histograms
fig = px.scatter(df, x='carat', y='price', 
                 marginal_x='box', 
                 marginal_y='violin',
                 color='cut',
                 facet_col='clarity',
                 facet_row='color',
                 title='Marginal Histograms of Carat and Price')
# figure size
fig.update_layout(height=1200, width=800)
fig.show()

## Video Plots

In [36]:
# Scatter plot
fig=px.scatter(df,x='carat', y='price',
               animation_frame='cut',
               title="Diamond price vs carat weight")
fig.show()
# save the animation plot
fig.write_html("scatter_animation.html")

### Save Animation plots

In [37]:
import plotly.express as px
import seaborn as sns
import os
from moviepy.editor import ImageSequenceClip

# Load the diamonds dataset
df = sns.load_dataset('diamonds')

# Check for missing values
if df.isnull().any().any():
    raise ValueError("The dataset contains missing values. Please handle them before plotting.")

# Create a directory to save frames
frames_dir = "frames"
os.makedirs(frames_dir, exist_ok=True)

# Extract unique values for the 'cut' column to iterate over
unique_cuts = df['cut'].unique()

# Save each frame as an image
for i, cut in enumerate(unique_cuts):
    # Filter the data for the current cut
    filtered_df = df[df['cut'] == cut]
    
    # Ensure filtered data is valid
    if filtered_df.empty:
        continue

    # Create the scatter plot for the current cut
    frame_fig = px.scatter(
        filtered_df, x='carat', y='price',
        color='color',
        title=f'Carat vs Price for {cut} Cut',
        size='depth',
        hover_data=['clarity']
    )
    
    # Save the frame image using Kaleido
    frame_filename = os.path.join(frames_dir, f"frame_{i:03d}.png")
    frame_fig.write_image(frame_filename, engine="kaleido")

# Create a GIF or MP4 using moviepy
image_files = [os.path.join(frames_dir, f) for f in sorted(os.listdir(frames_dir)) if f.endswith('.png')]
clip = ImageSequenceClip(image_files, fps=2)  # Adjust fps as needed
clip.write_gif("./03_plotly/animated_plot.gif", fps=2)    # Save as GIF
clip.write_videofile("./03_plotly/animated_plot.mp4", fps=1)  # Save as MP4
# save HD video
clip.write_videofile("./03_plotly/animated_plot_HD.mp4", fps=1, codec="libx264", preset="ultrafast", bitrate="3000k")
# Display the GIF in Jupyter Notebook
from IPython.display import Image
Image("./03_plotly/animated_plot.gif")

ModuleNotFoundError: No module named 'moviepy.editor'

## Other Plots